### PR TITLE
Add file icons

### PR DESCRIPTION
**Pull request by rciliberto**
## What?
This Pull Request adds icons to associate with .rkt files. They show up in the Project tab and in file tabs.

## Why?
I am currently taking a class that uses Racket and I was exploring alternatives to using Dr. Racket. I am familiar with the JetBrains suite of tools and came across this plugin. I tried it out and saw that icons were missing. 

Critique is welcome.

### CODE REVIEW

**Comment by aymanosman** [comment]
Thanks for the PR!

Before I merge, I'd like to ask for your feedback on the following issue.

File icons in IntelliJ follow a certain style that you can see in the examples below.
Contrast this with the file icon we will have for Racket once this PR is merged.

Screenshot 2022-10-15 at 11 29 25
Screenshot 2022-10-15 at 11 32 42

Do you think it is worth following the established style? If so, should it be implement in this PR or a follow up PR?

**Comment by rciliberto** [comment]
> Do you think it is worth following the established style?

While most of the official plugins from JetBrains do follow this style, there are some exceptions I have found. For instance, the official Svelte plugin from JetBrains uses the Svelte logo for .svelte files.

Screen Shot 2022-10-15 at 5 28 33 PM

That is to say, it may be up to personal preference. My opinion in this case is that the Racket logo is sufficient.

> Should it be implement in this PR or a follow up PR?

If you do prefer an Icon in the established style I am willing to find some time to work on creating one. Whether that is in this PR or a separate one, I will say is at your discretion.

**Comment by aymanosman** [comment]
Good point, I didn't know that they sometimes use the whole logo.

I do prefer the style where it doesn't use the logo, as it is less distracting. But because it is more work, I've just merged this PR.

Let me know if you would like to make an icon in the other style, otherwise I will prepare a release with the current merged PR.

**Comment by rciliberto** [comment]
Sure! I'll try to find some time to come up with one and make a separate PR for it.

**Pull request merged**
